export default function Random() {
    return <>
        <h1 className="text-xl">ldfdjskflkdjflkdjflkjdljflkdkfdkfkdjfkljdklfjkdjfjdlfkdkjfkldjfkdjkjfkdjfkjdkfjdLorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere accumsan quam, eget luctus est efficitur vel. Vestibulum volutpat libero eu quam ultricies mollis. Proin ut posuere sem, at gravida est. Donec lobortis porttitor tincidunt. Sed dictum ex molestie nunc pellentesque, nec lacinia mi vestibulum. Sed pulvinar nibh consequat sem imperdiet, id semper sem bibendum. Duis semper vitae odio vel imperdiet. Nam iaculis, est dignissim luctus pellentesque, neque enim placerat eros, id ultricies est mi id sapien. Aliquam eleifend eros ut ornare fringilla. Curabitur iaculis in massa a tincidunt. Nulla quis lobortis ex, sed varius est.

            Vivamus vestibulum est at est aliquet varius. Mauris dictum leo iaculis, pellentesque est at, mattis nibh. Pellentesque finibus ipsum viverra placerat aliquam. Ut commodo sollicitudin metus non luctus. Cras in lacus vestibulum, mollis magna eget, posuere ligula. Curabitur metus lorem, luctus pellentesque varius vitae, laoreet et dolor. In sodales pellentesque nunc non congue.

            Vivamus pulvinar odio ac lectus pretium dictum. Nunc ut quam dignissim, viverra diam ut, viverra justo. Praesent cursus, leo sit amet euismod molestie, ante ipsum semper neque, id accumsan leo sem ac augue. Curabitur mollis id erat et luctus. Praesent felis dolor, ultrices vitae justo eu, elementum venenatis nunc. Nunc mattis enim sapien, feugiat tristique urna feugiat at. Nulla facilisi. Sed a magna nunc. Pellentesque non dui eget nibh ullamcorper auctor vel a dui. Sed suscipit iaculis convallis. Fusce vitae odio nisi. Donec egestas orci pretium elit auctor tempus.

            Maecenas sollicitudin mollis consequat. Nullam viverra ipsum rhoncus, euismod libero eu, consequat enim. Sed ac magna leo. Nunc enim enim, aliquet quis eros sed, consectetur faucibus diam. In nec congue urna. Etiam eleifend felis quam, in semper est rutrum id. Fusce dictum, arcu eget interdum dapibus, dolor elit imperdiet erat, sit amet rutrum nisi ligula ac eros. Vestibulum ex lorem, sodales at purus at, mattis auctor ex.</h1>

    </>
}